development:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
<% if ENV["HEARTH_CROSS_PROCESS_SYSTEM_TEST"] == "1" %>
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.05.seconds
  message_retention: 1.hour
<% else %>
  adapter: test
<% end %>

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
